on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build & Test with xcodebuild
        run: |
          xcodebuild \
            -workspace YourApp.xcworkspace \
            -scheme kami-res-ai \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            clean build test
