on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode 16.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Print Xcode version
        run: xcodebuild -version

      - name: Build & Test
        run: |
          set -eux
          xcodebuild clean test \
            -project kami-res-ai.xcodeproj \
            -scheme "kami-res-ai" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5'
