on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      # Install & select Xcode 16.4 so project format 77 can be read
      - name: Setup Xcode 16.4
        uses: maxim-lobanov/setup-xcode@v3
        with:
          xcode-version: '16.4'

      # Verify that we’re now on Xcode 16.4
      - name: Print Xcode version
        run: xcodebuild -version

      # Build & run tests
      - name: Build & Test
        run: |
          set -eux
          xcodebuild clean test \
            -project kami-res-ai.xcodeproj \
            -scheme "kami-res-ai" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0'
